config/routes.rb
Rails.application.routes.draw do
  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
    resources :users, only: %i[show index] do
      resources :chat_rooms, only: %i[create show]
    end
  end

  resources :reactions, only: %i[create]
  resources :matching, only: %i[index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users, dependent: :destroy
  has_many :users, through: :chat_room_users, source: :user
  has_many :messages, dependent: :destroy
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user_chat_room_ids = ChatRoomUser.where(user_id: current_user.id).pluck(:chat_room_id)
    chat_room = ChatRoomUser.find_by(chat_room_id: current_user_chat_room_ids, user_id: params[:user_id])&.chat_room
    if chat_room.blank?
      chat_room = ChatRoom.create
      chat_room.chat_room_users.create(user_id: current_user.id)
      chat_room.chat_room_users.create(user_id: params[:user_id])
    end
    redirect_to user_chat_room_path(current_user, chat_room)
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @chat_room_user = @chat_room.chat_room_users.find_by(user_id: current_user.id)&.user
    @messages = Message.where(chat_room_id: @chat_room.id).order(:created_at)
  end
end

app/views/chat_rooms/show.html.erb
<div class="chat-room-show-page">
  <nav class="navbar navbar-light chat-room__header">
    <%= link_to matching_index_path, class: "nav-item nav-link" do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>

    <div class="chat-room__partner">
      <span class="chat-room__partner-name">
        <%= @chat_room_user.name %>
      </span>

      <% if @chat_room_user.profile_image.url.nil? %>
        <div class="chat-room__partner-default-img"></div>
      <% else %>
        <%= image_tag @chat_room_user.profile_image.url, class: "chat-room__partner-img" %>
      <% end %>
    </div>
  </nav>

  <div id="messages">
    <%= render @messages, chat_room_user: @chat_room_user %>
  </div>

  <form class="chat-room__message-form">
    <textarea data-behavior="chat_room_speaker" data-chat_room_id=<%= @chat_room.id %> placeholder=<%= t("views.chat_rooms.show.message_form") %>
    class="chat-room__message-form_textarea"></textarea>
  </form>
</div>