config/routes.rb
Rails.application.routes.draw do
  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
    resources :users, only: %i[show index] do
      resources :chat_rooms, only: %i[create show]
    end
  end

  resources :reactions, only: %i[create]
  resources :matching, only: %i[index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
  before_action :authenticate_user!

  def index
    got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: :like).pluck(:from_user_id)
    @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: :like).map(&:to_user)
    @user = User.find(current_user.id)
  end
end

app/views/matching/index.html.erb
<div class="matching-index-page">
  <%= render "partial/navbar", user: @user %>
  <div class="matching">
    <p class="matching-title ml-3">
      <%= Message.model_name.human %>
    </p>
    <p class="matching-num">
      <%= "#{t("views.matching.index.matching_num")} #{@match_users.size}#{t("views.matching.index.count")}" %>
    </p>
    <div class="matching__list">
      <% if @match_users.present? %>
        <% @match_users.each do |user| %>
          <%= link_to user_chat_rooms_path(user_id: user.id), method: :post do %>
          <div class="matching__person">
            <% if user.profile_image.url.nil? %>
              <div class="matching__person-default-img"></div>
            <% else %>
              <%= image_tag user.profile_image.url, class: "matching__person-img" %>
            <% end %>
            <div class="matching__person-name">
              <%= user.name %>
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>